name: "$(Build.DefinitionName) #$(Build.BuildId)"

trigger: none # Manual Publish
pr: none # GitHub Actions handle PRs

parameters:
  - name: AgentPoolName
    displayName: Agent pool name
    type: string
    default: ADO Windows Server 2022

  - name: AgentName
    displayName: Agent name - single char for any
    type: string
    default: " "

resources:
  repositories:
    - repository: self
      type: git

  containers:
    - container: Windows
      image: base/mcr-dotnet-sdk-6.0-servercore-ltsc2022:latest
      endpoint: xperienceagentshub.azurecr.io

variables:
  - name: SIGN_FILE
    value: true

stages:
  - stage: Build
    jobs:
      - job: Build
        displayName: Build, Sign, Test & Pack

        pool:
          name: ${{ parameters.AgentPoolName }}
          ${{ if ne(length(parameters.AgentName), 1) }}:
            demands:
              - Agent.Name -equals ${{ parameters.AgentName }}
        container: Windows

        variables:
          - group: Code Sign KV Auth

          - name: Configuration
            value: Release

          - name: ProjectFolder
            value: src/Kentico.Xperience.Algolia

          - name: ProjectFilePath
            value: src/Kentico.Xperience.Algolia/Kentico.Xperience.Algolia.csproj

        steps:
          - task: PowerShell@2
            displayName: Set Node.js version from package.json
            inputs:
              targetType: inline
              script: |
                $fileContent = Get-Content -Path './${{ variables.ProjectFolder }}/Admin/Client/package.json' -Raw
                $jsonObject = ConvertFrom-Json -InputObject $fileContent

                # Get the value of engines.node
                $enginesNode = $jsonObject.engines.node
                Write-Host "Required Node version $enginesNode"
                Write-Host "##vso[task.setvariable variable=PACKAGE_JSON_NODE_VERSION]$enginesNode"

          - task: UseNode@1
            displayName: "Install Node.js from package.json version"
            inputs:
              version: $(PACKAGE_JSON_NODE_VERSION)

          - task: UseDotNet@2
            displayName: Select dotnet version
            inputs:
              packageType: sdk
              useGlobalJson: true

          - task: DotNetCoreCLI@2
            displayName: Restore dotnet tools
            inputs:
              command: custom
              custom: tool
              arguments: restore
              workingDirectory: $(System.DefaultWorkingDirectory)

          - task: DotNetCoreCLI@2
            displayName: Restore dependencies
            inputs:
              command: restore
              projects: ${{ variables.ProjectFilePath }}
              feedsToUse: select
              restoreArguments: --locked-mode

          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: build
              projects: ${{ variables.ProjectFilePath }}
              configuration: ${{ variables.Configuration }}
              arguments: --no-restore
            env:
              AuthenticodeClientSecret: $(AuthenticodeClientSecret)

          - task: DotNetCoreCLI@2
            displayName: Create NuGet package
            inputs:
              command: pack
              packagesToPack: ${{ variables.ProjectFilePath }}
              configuration: ${{ variables.Configuration }}
              packDirectory: $(System.DefaultWorkingDirectory)/packages
              includesymbols: true
              nobuild: true
              versioningScheme: off

          - publish: $(System.DefaultWorkingDirectory)/packages
            displayName: Publish NuGet package as artifact
            artifact: artifact

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      - stage: PublishNuGetPackages
        displayName: Publish NuGet packages
        dependsOn: Build

        jobs:
          - deployment: PublishNuGetPackages
            displayName: Publish NuGet packages

            pool:
              name: ${{ parameters.AgentPoolName }}
              ${{ if ne(length(parameters.AgentName), 1) }}:
                demands:
                  - Agent.Name -equals ${{ parameters.AgentName }}
            container: Windows

            environment: integrations-release-nuget
            workspace:
              clean: all
            strategy:
              runOnce:
                deploy:
                  steps:
                    - checkout: none

                    - task: NuGetToolInstaller@1
                      displayName: Install latest nuget.exe
                      inputs:
                        versionSpec: ">=5.6"
                        checkLatest: true

                    - task: NuGetAuthenticate@1
                      displayName: NuGet Authenticate

                    - task: NuGetCommand@2
                      displayName: NuGet push
                      inputs:
                        command: push
                        packagesToPush: $(Pipeline.Workspace)/artifact/*.nupkg
                        nuGetFeedType: external
                        publishFeedCredentials: nuget.org
                        allowPackageConflicts: true
