name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  javascript:
      name: Build Javascript
      runs-on: ubuntu-latest
      steps:
        - name: Install NodeJS
          uses: actions/setup-node@v2
          with:
            node-version: 16
        - name: Code Checkout
          uses: actions/checkout@v2
        - name: Install Dependencies
          run: cd src/admin/client && npm ci
        - name: Code Linting
          run: npm run lint
  net6:
    name: Build .NET 6.0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/Kentico.Xperience.Algolia.csproj
    - name: Build
      run: dotnet build src/Kentico.Xperience.Algolia.csproj --no-restore